### ISSUE TITLE
Maya: Loader sometimes doesn't refresh when assets are changed

### ISSUE THREAD

**Issue by antirotor** [pypeclub/pype#196] opened 2020-05-31 12:28 UTC
## Problem

Client reported issue when using  Loader in Maya that sometimes subset part of asset loader window doesn't refresh when another asset is selected, leading to loading wrong subsets to scene.

**Comment by kalisp** [comment] 2020-08-28 12:32
Couldn't reproduce, is there more information in what state this occurred?

**Comment by antirotor** [comment] 2020-09-09 08:37
Nope, it never happened to me. One client reported it multiple times.

**Comment by mkolar** [comment] 2021-02-16 19:40
I'm closing this. Never occured again and can't be reproduced

**Closed by mkolar** 2021-02-16 19:40 UTC
Labels: MEDIUM, bug, client, host: Maya
